### ISSUE TITLE
Update to latest Hono version

### ISSUE THREAD

**Issue by calohmn** [eclipse-hono/hono-extras#12]
An update to the current Hono version as dependency should be done.

**Comment by calohmn** [comment]
@sophokles73 @b-abel Currently there is a `hono-legal` maven dependency here:
https://github.com/eclipse/hono-extras/blob/fdfceec97b73f5fa20e75d75aa084d42a4b75e8a/protocol-gateway/mqtt-protocol-gateway-template/pom.xml#L64-L67

However, for Hono versions > 1.7, the corresponding artifact isn't published to maven central anymore (see [here](https://mvnrepository.com/artifact/org.eclipse.hono/hono-legal)).
Should we restore publishing the legal artifact to maven central, or rather include a license folder here?

**Comment by sophokles73** [comment]
I cannot recall why the hono-legal artifact is not being published anymore and/or whether this change was made deliberately. In any case, I do not see why we shouldn't start publishing it again ...
