### ISSUE TITLE
Icon files could be commercial licensed

### ISSUE THREAD

**Issue by rahulmohang** [eclipse-hono/hono-extras#31]
Hi, 

The following files contains mentions of fontawesome commercial license:

https://github.com/eclipse-hono/hono-extras/blob/master/device-management-ui/src/assets/images/sort-up-solid.svg
https://github.com/eclipse-hono/hono-extras/blob/master/device-management-ui/src/assets/images/sort-solid.svg

The text of the reference is as follows:

"
Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. 
"

Are the files licensed under commercial license?

**Comment by calohmn** [comment]
This question has been discussed in the PR that added these files - see https://github.com/eclipse-hono/hono-extras/pull/25#issuecomment-1787195654.
We are using the free version of font awesome here. 
This has been confirmed here: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10922#note_1293335.

**Comment by rahulmohang** [comment]
Ok, Thank you for pointing me towards this. I knew that I had done this, but could not find how I communicated with the project. Now, I recollect that it was via email.
